---
pipeline:
  alwaysEmailList: ljohnson@dettonville.org
  runInParallel: true
  maxRandomDelaySeconds: 60

  buildImageName: "ansible/ansible-runner"
  buildDir: "image"
  buildArgs:
    IMAGE_REGISTRY: media.johnson.int:5000

  buildImageList:
    - buildArgs:
        ANSIBLE_CORE_VERSION: "2.16"
        PYTHON_VERSION: "3.10"
      buildTags:
        - stable-2.16-py3.10
    - buildArgs:
        ANSIBLE_CORE_VERSION: "latest"
        PYTHON_VERSION: "3.10"
      buildTags:
        - latest-py3.10

    - buildArgs:
        ANSIBLE_CORE_VERSION: "2.16"
        PYTHON_VERSION: "3.11"
      buildTags:
        - stable-2.16-py3.11
    - buildArgs:
        ANSIBLE_CORE_VERSION: "2.18"
        PYTHON_VERSION: "3.11"
      buildTags:
        - stable-2.18-py3.11
    - buildArgs:
        ANSIBLE_CORE_VERSION: "2.19"
        PYTHON_VERSION: "3.11"
      buildTags:
        - stable-2.19-py3.11

    - buildArgs:
        ANSIBLE_CORE_VERSION: "2.18"
        PYTHON_VERSION: "3.12"
      buildTags:
        - stable-2.18-py3.12
    - buildArgs:
        ANSIBLE_CORE_VERSION: "2.19"
        PYTHON_VERSION: "3.12"
      buildTags:
        - stable-2.19-py3.12
    - buildArgs:
        ANSIBLE_CORE_VERSION: "latest"
        PYTHON_VERSION: "3.12"
      buildTags:
        - latest-py3.12

    - buildArgs:
        ANSIBLE_CORE_VERSION: "2.18"
        PYTHON_VERSION: "3.13"
      buildTags:
        - stable-2.18-py3.13
    - buildArgs:
        ANSIBLE_CORE_VERSION: "2.19"
        PYTHON_VERSION: "3.13"
      buildTags:
        - stable-2.19-py3.13
    - buildArgs:
        ANSIBLE_CORE_VERSION: "latest"
        PYTHON_VERSION: "3.13"
      buildTags:
        - latest-py3.13
